# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'Moon_Moon_AYg0XejcJn4pDFUjzOOD'
      cliSources: '.'

  - script: |
      # Download and install SonarQube Scanner
      curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      unzip sonar-scanner.zip
      mv sonar-scanner-* sonar-scanner
      mkdir -p $(Agent.ToolsDirectory)/.sonarqube/conf
      echo "sonar.scanner.home=$(Agent.HomeDirectory)/sonar-scanner" >> $(Agent.ToolsDirectory)/.sonarqube/conf/sonar-scanner.properties
    displayName: 'Install SonarQube Scanner'

  - bash: |
      # Verify the SonarQube Scanner installation
      ls $(Agent.HomeDirectory)/sonar-scanner/bin
    displayName: 'Verify SonarQube Scanner Installation'


  - bash: |
      # Run SonarQube analysis
      sonar-scanner
    displayName: 'Run SonarQube Analysis'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - bash: |
      # Write your commands here
      echo '------------------------------------pwd------------------------------'
      pwd
      node -v
      npm --version
      npm cache clean --force
      npm install
      echo "------------------------------------pwd--------------------------------"
      pwd
    displayName: 'Build Application'



  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'

  - bash: |
      # Write your commands here
      echo "------------"
      pwd
      ls $(build.artifactstagingdirectory)
    displayName: 'Bash Script'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: juice-shop-drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'juice-drop'
