# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:


- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- bash: |
   # Write your commands here
   
   echo 'Hello world'
   pwd
   node -v
   npm --version
   npm cache clean --force
   npm install
   npm install tar-stream@1.6.2
   
  displayName: 'Build Application'



- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     **/*
    TargetFolder: '$(build.artifactstagingdirectory)'

- bash: |
   # Write your commands here
   
   echo "------------"
   
   pwd 
   ls $(build.artifactstagingdirectory)
  displayName: 'Bash Script'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).gz'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: juice-shop-drop'
  inputs:
    ArtifactName: 'juice-drop'
